baseurl: https://example.org/
title: Creative portfolio
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2016 Your name or company'
  description: Describe your website
  email: robwhickman@gmail.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - I am a professional data scientist who likes to play around with reproducing plots
    - Based in London
  social:
    email: robwhickman@gmail.com
    twitter: https://twitter.com/robwhickman
  style: default
