theme: hugo-frances-theme
baseurl: https://example.com
languageCode: en-us
sectionPagesMenu: main
params:
  author: Frances Hodgkins
  description: Landscape and still-life painter from New Zealand
  email: frances@hodgkins.io
  name: Frances Hodgkins
