baseurl: www.plots.gg
languageCode: en
defaultContentLanguage: en
title: Plots.GG
theme: hugo-theme-dream
params:
  author: Robert Hickman
  avatar: avatar.jpg
  background: '#f4e9f7'
  email: g1enyy0ung@gmail.com
  headerTitle: Plots.GG
  linkColor: seagreen
  motto: A place for some plots, mostly in R, mostly using {ggplot2}
  siteStartYear: 2021
