baseurl: https://plots.gg
title: Plots.GG
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: 'none'
  description: Some plots, mostly in R, mostly using {ggplot2}
  email: robwhickman@gmail.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
  sidebarAbout:
    - I am a data scientist and former academic
    - Originally from and currently based in London
  social:
    github: https://github.com/RobWHickman
    twitter: https://twitter.com/robwhickman
  style: default
